server:
  port: 8002

  # mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.gzq.springcloud.pojo    # 实体类所在的位置
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloudB-provide-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provide-dept8002

info:
  app.name: com.gzq
  company.name: com.zji
